[package]
name = "monte_carlo_tree_search"
version = "0.1.0"
edition = "2021"

[lib]
name = "monte_carlo_tree_search"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
rand = "0.8"